package javacesocial.webservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AutorizadorWS", targetNamespace = "http://service.webservice.social.javace.org/")
public interface AutorizadorWS {

	/**
	 * 
	 * @param numeroDoCartao
	 * @return returns java.lang.Integer
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "servico", targetNamespace = "http://service.webservice.social.javace.org/", className = "org.javace.social.webservice.service.Servico")
	@ResponseWrapper(localName = "servicoResponse", targetNamespace = "http://service.webservice.social.javace.org/", className = "org.javace.social.webservice.service.ServicoResponse")
	public Integer servico(
			@WebParam(name = "numeroDoCartao", targetNamespace = "") String numeroDoCartao);

}
