package javacesocial.webservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * webService service = new webService();
 * AutorizadorWS portType = service.getAutorizadorWSImplPort();
 * portType.servico(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "webService", targetNamespace = "http://v1.webservice.javacesocial", wsdlLocation = "http://localhost:8080/SpringWebService/webservice/v1/WebService?wsdl")
public class WebService extends Service {

	private final static URL WEBSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(javacesocial.webservice.v1.WebService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = javacesocial.webservice.v1.WebService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/SpringWebService/webservice/v1/WebService?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/SpringWebService/webservice/v1/WebService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WEBSERVICE_WSDL_LOCATION = url;
	}

	public WebService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WebService() {
		super(WEBSERVICE_WSDL_LOCATION, new QName(
				"http://v1.webservice.javacesocial", "webService"));
	}

	/**
	 * 
	 * @return returns AutorizadorWS
	 */
	@WebEndpoint(name = "AutorizadorWSImplPort")
	public AutorizadorWS getAutorizadorWSImplPort() {
		return super.getPort(new QName("http://v1.webservice.javacesocial",
				"AutorizadorWSImplPort"), AutorizadorWS.class);
	}

}
